services:
  
  db:
    image: postgres:17
    container_name: app_database
    environment:
      POSTGRES_USER: dev
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
        
        
  redis:
    image: redis:7.0
    container_name: app_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped
    networks:
      - app-network
        
volumes:
  pgdata:
  redisdata:
  
networks:
  app-network:
    driver: bridge
        
      